/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.12.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

// 共通の clean/build/javadoc など最小タスク だけ確保し、CI で gradle build と叩けばサブも一括実行。
// java-library を root に付けても動きますが、api/implementation が空で生成される "空ライブラリ" が出来上がり、アーティファクトが冗長になります​
plugins {
    java
    id("com.diffplug.spotless") version "7.0.3"
}

subprojects {
    apply(plugin = "java-library")
    java {
        toolchain { languageVersion.set(JavaLanguageVersion.of(21)) }
    }

    tasks.withType<Test> {
        useJUnitPlatform()
    }

    apply(plugin = "com.diffplug.spotless")
    spotless {
        java {
            googleJavaFormat("1.17.0")
            target("src/**/*.java")
            removeUnusedImports()
        }
    }
}